SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION GenerateID(@tableName VARCHAR(20), @guid UNIQUEIDENTIFIER)
RETURNS VARCHAR(56)
AS
BEGIN
	DECLARE @newID VARCHAR(56)

	SELECT @newID = @tableName + CAST(@guid AS VARCHAR(36))

	RETURN @newID
END
GO

