name: Build PR to main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore "AltexFood Delivery/AltexFood Delivery.sln"
    - name: Build
      run: dotnet build "AltexFood Delivery/AltexFood Delivery.sln" --no-restore
    - name: Test
      run: dotnet test "AltexFood Delivery/AltexFood Delivery.sln" --no-build --verbosity normal
